name: Format

on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/creyD/prettier_action
      - name: Run prettier
        uses: creyD/prettier_action@v4.2
        with:
          dry: True
          prettier_options: --check .
